// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkins.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO check_ins (thread_id, date, deadline)
VALUES ($1, $2, $3)
RETURNING id, thread_id, date, deadline, status, resolved_at, created_at
`

type CreateCheckInParams struct {
	ThreadID uuid.UUID
	Date     pgtype.Date
	Deadline pgtype.Date
}

func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, createCheckIn, arg.ThreadID, arg.Date, arg.Deadline)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Date,
		&i.Deadline,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPendingCheckIn = `-- name: GetCurrentPendingCheckIn :one
SELECT check_ins.id, check_ins.thread_id, check_ins.date, check_ins.deadline, check_ins.status, check_ins.resolved_at, check_ins.created_at
FROM check_ins
JOIN threads ON threads.id = check_ins.thread_id
JOIN contacts ON contacts.id = threads.contact_id
WHERE check_ins.thread_id = $1
  AND check_ins.status = 'pending'
  AND contacts.user_id = $2
`

type GetCurrentPendingCheckInParams struct {
	ThreadID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetCurrentPendingCheckIn(ctx context.Context, arg GetCurrentPendingCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCurrentPendingCheckIn, arg.ThreadID, arg.UserID)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Date,
		&i.Deadline,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const rescheduleCheckIn = `-- name: RescheduleCheckIn :one
UPDATE check_ins
SET date = $2, deadline = $3
FROM threads, contacts
WHERE check_ins.id = $1
  AND check_ins.thread_id = threads.id
  AND threads.contact_id = contacts.id
  AND contacts.user_id = $4
  AND check_ins.status = 'pending'
RETURNING check_ins.id, check_ins.thread_id, check_ins.date, check_ins.deadline, check_ins.status, check_ins.resolved_at, check_ins.created_at
`

type RescheduleCheckInParams struct {
	ID       uuid.UUID
	Date     pgtype.Date
	Deadline pgtype.Date
	UserID   uuid.UUID
}

func (q *Queries) RescheduleCheckIn(ctx context.Context, arg RescheduleCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, rescheduleCheckIn,
		arg.ID,
		arg.Date,
		arg.Deadline,
		arg.UserID,
	)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Date,
		&i.Deadline,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const resolveCheckIn = `-- name: ResolveCheckIn :one
UPDATE check_ins
SET status = $2, resolved_at = now()
FROM threads, contacts
WHERE check_ins.id = $1
  AND check_ins.thread_id = threads.id
  AND threads.contact_id = contacts.id
  AND contacts.user_id = $3
RETURNING check_ins.id, check_ins.thread_id, check_ins.date, check_ins.deadline, check_ins.status, check_ins.resolved_at, check_ins.created_at
`

type ResolveCheckInParams struct {
	ID     uuid.UUID
	Status CheckinStatus
	UserID uuid.UUID
}

func (q *Queries) ResolveCheckIn(ctx context.Context, arg ResolveCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, resolveCheckIn, arg.ID, arg.Status, arg.UserID)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Date,
		&i.Deadline,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}
