// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_methods.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createContactMethod = `-- name: CreateContactMethod :one
INSERT INTO contact_methods (contact_id, type, value)
VALUES ($1, $2, $3)
RETURNING id, contact_id, type, value, created_at
`

type CreateContactMethodParams struct {
	ContactID uuid.UUID
	Type      string
	Value     string
}

func (q *Queries) CreateContactMethod(ctx context.Context, arg CreateContactMethodParams) (ContactMethod, error) {
	row := q.db.QueryRow(ctx, createContactMethod, arg.ContactID, arg.Type, arg.Value)
	var i ContactMethod
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContactMethod = `-- name: DeleteContactMethod :exec
DELETE FROM contact_methods
USING contacts
WHERE contact_methods.id = $1
  AND contact_methods.contact_id = contacts.id
  AND contacts.user_id = $2
`

type DeleteContactMethodParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteContactMethod(ctx context.Context, arg DeleteContactMethodParams) error {
	_, err := q.db.Exec(ctx, deleteContactMethod, arg.ID, arg.UserID)
	return err
}

const listContactMethodsByContact = `-- name: ListContactMethodsByContact :many
SELECT contact_methods.id, contact_methods.contact_id, contact_methods.type, contact_methods.value, contact_methods.created_at
FROM contact_methods
JOIN contacts ON contacts.id = contact_methods.contact_id
WHERE contact_methods.contact_id = $1 AND contacts.user_id = $2
`

type ListContactMethodsByContactParams struct {
	ContactID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ListContactMethodsByContact(ctx context.Context, arg ListContactMethodsByContactParams) ([]ContactMethod, error) {
	rows, err := q.db.Query(ctx, listContactMethodsByContact, arg.ContactID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactMethod
	for rows.Next() {
		var i ContactMethod
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
