// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getContactByID = `-- name: GetContactByID :one
SELECT id, name, role, status, created_at, updated_at, user_id
FROM contacts
WHERE id = $1 AND user_id = $2
`

type GetContactByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, name, role, status, created_at, updated_at, user_id FROM contacts
WHERE status = 'active' AND user_id = $1
ORDER BY name
`

func (q *Queries) ListContacts(ctx context.Context, userID uuid.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByName = `-- name: ListContactsByName :many
SELECT id, name, role, status, created_at, updated_at, user_id
FROM contacts
WHERE name = $1 AND user_id = $2
`

type ListContactsByNameParams struct {
	Name   string
	UserID uuid.UUID
}

func (q *Queries) ListContactsByName(ctx context.Context, arg ListContactsByNameParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByName, arg.Name, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
