// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckinStatus string

const (
	CheckinStatusPending   CheckinStatus = "pending"
	CheckinStatusCompleted CheckinStatus = "completed"
	CheckinStatusSkipped   CheckinStatus = "skipped"
	CheckinStatusMissed    CheckinStatus = "missed"
)

func (e *CheckinStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckinStatus(s)
	case string:
		*e = CheckinStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckinStatus: %T", src)
	}
	return nil
}

type NullCheckinStatus struct {
	CheckinStatus CheckinStatus
	Valid         bool // Valid is true if CheckinStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckinStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CheckinStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckinStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckinStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckinStatus), nil
}

type ContactStatus string

const (
	ContactStatusActive   ContactStatus = "active"
	ContactStatusArchived ContactStatus = "archived"
)

func (e *ContactStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactStatus(s)
	case string:
		*e = ContactStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactStatus: %T", src)
	}
	return nil
}

type NullContactStatus struct {
	ContactStatus ContactStatus
	Valid         bool // Valid is true if ContactStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContactStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContactStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContactStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContactStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContactStatus), nil
}

type ThreadStatus string

const (
	ThreadStatusActive   ThreadStatus = "active"
	ThreadStatusArchived ThreadStatus = "archived"
)

func (e *ThreadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ThreadStatus(s)
	case string:
		*e = ThreadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ThreadStatus: %T", src)
	}
	return nil
}

type NullThreadStatus struct {
	ThreadStatus ThreadStatus
	Valid        bool // Valid is true if ThreadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullThreadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ThreadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ThreadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullThreadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ThreadStatus), nil
}

type Campaign struct {
	ID         uuid.UUID
	Name       string
	Purpose    pgtype.Text
	StartDate  pgtype.Date
	PacingRule pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type CheckIn struct {
	ID         uuid.UUID
	ThreadID   uuid.UUID
	Date       pgtype.Date
	Deadline   pgtype.Date
	Status     CheckinStatus
	ResolvedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Contact struct {
	ID        uuid.UUID
	Name      string
	Role      pgtype.Text
	Status    ContactStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserID    uuid.UUID
}

type ContactMethod struct {
	ID        uuid.UUID
	ContactID uuid.UUID
	Type      string
	Value     string
	CreatedAt pgtype.Timestamptz
}

type ContactTag struct {
	ContactID uuid.UUID
	TagID     uuid.UUID
}

type Tag struct {
	ID     uuid.UUID
	Name   string
	UserID uuid.UUID
}

type Thread struct {
	ID                  uuid.UUID
	ContactID           uuid.UUID
	Label               string
	CadenceIntervalDays *int32
	Status              ThreadStatus
	CampaignID          *uuid.UUID
	EmailEnabled        pgtype.Bool
	PushEnabled         pgtype.Bool
	CreatedAt           pgtype.Timestamptz
}

type ThreadTag struct {
	ThreadID uuid.UUID
	TagID    uuid.UUID
}
