// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error)
	ListContacts(ctx context.Context, userID uuid.UUID) ([]Contact, error)
	ListContactsByName(ctx context.Context, arg ListContactsByNameParams) ([]Contact, error)
}

var _ Querier = (*Queries)(nil)
