// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTagToContact(ctx context.Context, arg AddTagToContactParams) error
	AddTagToThread(ctx context.Context, arg AddTagToThreadParams) error
	ArchiveContact(ctx context.Context, arg ArchiveContactParams) error
	ArchiveThread(ctx context.Context, arg ArchiveThreadParams) error
	CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateContactMethod(ctx context.Context, arg CreateContactMethodParams) (ContactMethod, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	DeleteContactMethod(ctx context.Context, arg DeleteContactMethodParams) error
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error)
	GetCurrentPendingCheckIn(ctx context.Context, arg GetCurrentPendingCheckInParams) (CheckIn, error)
	GetThreadByCheckInID(ctx context.Context, arg GetThreadByCheckInIDParams) (Thread, error)
	GetThreadByID(ctx context.Context, arg GetThreadByIDParams) (Thread, error)
	ListContactMethodsByContact(ctx context.Context, arg ListContactMethodsByContactParams) ([]ContactMethod, error)
	ListContacts(ctx context.Context, userID uuid.UUID) ([]Contact, error)
	ListContactsByName(ctx context.Context, arg ListContactsByNameParams) ([]Contact, error)
	ListTags(ctx context.Context, userID uuid.UUID) ([]Tag, error)
	ListTagsForContact(ctx context.Context, arg ListTagsForContactParams) ([]Tag, error)
	ListTagsForThread(ctx context.Context, arg ListTagsForThreadParams) ([]Tag, error)
	ListThreadsByContact(ctx context.Context, arg ListThreadsByContactParams) ([]Thread, error)
	RemoveTagFromContact(ctx context.Context, arg RemoveTagFromContactParams) error
	RemoveTagFromThread(ctx context.Context, arg RemoveTagFromThreadParams) error
	RescheduleCheckIn(ctx context.Context, arg RescheduleCheckInParams) (CheckIn, error)
	ResolveCheckIn(ctx context.Context, arg ResolveCheckInParams) (CheckIn, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
}

var _ Querier = (*Queries)(nil)
