// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagToContact = `-- name: AddTagToContact :exec
INSERT INTO contact_tags (contact_id, tag_id)
SELECT $1, $2
WHERE EXISTS (SELECT 1 FROM contacts WHERE contacts.id = $1 AND contacts.user_id = $3)
  AND EXISTS (SELECT 1 FROM tags WHERE tags.id = $2 AND tags.user_id = $3)
`

type AddTagToContactParams struct {
	ContactID uuid.UUID
	TagID     uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) AddTagToContact(ctx context.Context, arg AddTagToContactParams) error {
	_, err := q.db.Exec(ctx, addTagToContact, arg.ContactID, arg.TagID, arg.UserID)
	return err
}

const addTagToThread = `-- name: AddTagToThread :exec
INSERT INTO thread_tags (thread_id, tag_id)
SELECT $1, $2
WHERE EXISTS (
    SELECT 1 FROM threads JOIN contacts ON contacts.id = threads.contact_id
    WHERE threads.id = $1 AND contacts.user_id = $3
  )
  AND EXISTS (SELECT 1 FROM tags WHERE tags.id = $2 AND tags.user_id = $3)
`

type AddTagToThreadParams struct {
	ThreadID uuid.UUID
	TagID    uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) AddTagToThread(ctx context.Context, arg AddTagToThreadParams) error {
	_, err := q.db.Exec(ctx, addTagToThread, arg.ThreadID, arg.TagID, arg.UserID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, user_id)
VALUES ($1, $2)
RETURNING id, name, user_id
`

type CreateTagParams struct {
	Name   string
	UserID uuid.UUID
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.UserID)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.UserID)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, user_id FROM tags
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, userID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForContact = `-- name: ListTagsForContact :many
SELECT tags.id, tags.name, tags.user_id
FROM tags
JOIN contact_tags ON contact_tags.tag_id = tags.id
JOIN contacts ON contacts.id = contact_tags.contact_id
WHERE contact_tags.contact_id = $1
  AND tags.user_id = $2
  AND contacts.user_id = $2
`

type ListTagsForContactParams struct {
	ContactID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ListTagsForContact(ctx context.Context, arg ListTagsForContactParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForContact, arg.ContactID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForThread = `-- name: ListTagsForThread :many
SELECT tags.id, tags.name, tags.user_id
FROM tags
JOIN thread_tags ON thread_tags.tag_id = tags.id
JOIN threads ON threads.id = thread_tags.thread_id
JOIN contacts ON contacts.id = threads.contact_id
WHERE thread_tags.thread_id = $1
  AND tags.user_id = $2
  AND contacts.user_id = $2
`

type ListTagsForThreadParams struct {
	ThreadID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListTagsForThread(ctx context.Context, arg ListTagsForThreadParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForThread, arg.ThreadID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromContact = `-- name: RemoveTagFromContact :exec
DELETE FROM contact_tags
USING contacts
WHERE contact_tags.contact_id = $1
  AND contact_tags.tag_id = $2
  AND contact_tags.contact_id = contacts.id
  AND contacts.user_id = $3
`

type RemoveTagFromContactParams struct {
	ContactID uuid.UUID
	TagID     uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveTagFromContact(ctx context.Context, arg RemoveTagFromContactParams) error {
	_, err := q.db.Exec(ctx, removeTagFromContact, arg.ContactID, arg.TagID, arg.UserID)
	return err
}

const removeTagFromThread = `-- name: RemoveTagFromThread :exec
DELETE FROM thread_tags
USING threads, contacts
WHERE thread_tags.thread_id = $1
  AND thread_tags.tag_id = $2
  AND thread_tags.thread_id = threads.id
  AND threads.contact_id = contacts.id
  AND contacts.user_id = $3
`

type RemoveTagFromThreadParams struct {
	ThreadID uuid.UUID
	TagID    uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RemoveTagFromThread(ctx context.Context, arg RemoveTagFromThreadParams) error {
	_, err := q.db.Exec(ctx, removeTagFromThread, arg.ThreadID, arg.TagID, arg.UserID)
	return err
}
