// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveThread = `-- name: ArchiveThread :exec
UPDATE threads
SET status = 'archived'
FROM contacts
WHERE threads.id = $1
  AND threads.contact_id = contacts.id
  AND contacts.user_id = $2
`

type ArchiveThreadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ArchiveThread(ctx context.Context, arg ArchiveThreadParams) error {
	_, err := q.db.Exec(ctx, archiveThread, arg.ID, arg.UserID)
	return err
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads (contact_id, label, cadence_interval_days)
VALUES ($1, $2, $3)
RETURNING id, contact_id, label, cadence_interval_days, status, campaign_id, email_enabled, push_enabled, created_at
`

type CreateThreadParams struct {
	ContactID           uuid.UUID
	Label               string
	CadenceIntervalDays *int32
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.ContactID, arg.Label, arg.CadenceIntervalDays)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Label,
		&i.CadenceIntervalDays,
		&i.Status,
		&i.CampaignID,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadByCheckInID = `-- name: GetThreadByCheckInID :one
SELECT threads.id, threads.contact_id, threads.label, threads.cadence_interval_days, threads.status, threads.campaign_id, threads.email_enabled, threads.push_enabled, threads.created_at
FROM threads
JOIN check_ins ON check_ins.thread_id = threads.id
JOIN contacts ON contacts.id = threads.contact_id
WHERE check_ins.id = $1 AND contacts.user_id = $2
`

type GetThreadByCheckInIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetThreadByCheckInID(ctx context.Context, arg GetThreadByCheckInIDParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadByCheckInID, arg.ID, arg.UserID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Label,
		&i.CadenceIntervalDays,
		&i.Status,
		&i.CampaignID,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadByID = `-- name: GetThreadByID :one
SELECT threads.id, threads.contact_id, threads.label, threads.cadence_interval_days, threads.status, threads.campaign_id, threads.email_enabled, threads.push_enabled, threads.created_at
FROM threads
JOIN contacts ON contacts.id = threads.contact_id
WHERE threads.id = $1 AND contacts.user_id = $2
`

type GetThreadByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetThreadByID(ctx context.Context, arg GetThreadByIDParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadByID, arg.ID, arg.UserID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Label,
		&i.CadenceIntervalDays,
		&i.Status,
		&i.CampaignID,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listThreadsByContact = `-- name: ListThreadsByContact :many
SELECT threads.id, threads.contact_id, threads.label, threads.cadence_interval_days, threads.status, threads.campaign_id, threads.email_enabled, threads.push_enabled, threads.created_at
FROM threads
JOIN contacts ON contacts.id = threads.contact_id
WHERE threads.contact_id = $1
  AND contacts.user_id = $2
  AND ($3::thread_status IS NULL OR threads.status = $3)
  AND (
    $4::uuid IS NULL
    OR EXISTS (
        SELECT 1 FROM thread_tags
        WHERE thread_tags.thread_id = threads.id
        AND thread_tags.tag_id = $4
    )
)
`

type ListThreadsByContactParams struct {
	ContactID uuid.UUID
	UserID    uuid.UUID
	Status    NullThreadStatus
	TagID     *uuid.UUID
}

func (q *Queries) ListThreadsByContact(ctx context.Context, arg ListThreadsByContactParams) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsByContact,
		arg.ContactID,
		arg.UserID,
		arg.Status,
		arg.TagID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Label,
			&i.CadenceIntervalDays,
			&i.Status,
			&i.CampaignID,
			&i.EmailEnabled,
			&i.PushEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
