// Code generated by MockGen. DO NOT EDIT.
// Source: db/sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=db/sqlc/querier.go -destination=mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/P4rz1val22/outreach-tool/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetContactByID mocks base method.
func (m *MockQuerier) GetContactByID(ctx context.Context, arg sqlc.GetContactByIDParams) (sqlc.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByID", ctx, arg)
	ret0, _ := ret[0].(sqlc.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByID indicates an expected call of GetContactByID.
func (mr *MockQuerierMockRecorder) GetContactByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByID", reflect.TypeOf((*MockQuerier)(nil).GetContactByID), ctx, arg)
}

// ListContacts mocks base method.
func (m *MockQuerier) ListContacts(ctx context.Context, userID uuid.UUID) ([]sqlc.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContacts", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContacts indicates an expected call of ListContacts.
func (mr *MockQuerierMockRecorder) ListContacts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContacts", reflect.TypeOf((*MockQuerier)(nil).ListContacts), ctx, userID)
}

// ListContactsByName mocks base method.
func (m *MockQuerier) ListContactsByName(ctx context.Context, arg sqlc.ListContactsByNameParams) ([]sqlc.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContactsByName", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContactsByName indicates an expected call of ListContactsByName.
func (mr *MockQuerierMockRecorder) ListContactsByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContactsByName", reflect.TypeOf((*MockQuerier)(nil).ListContactsByName), ctx, arg)
}
