// Code generated by MockGen. DO NOT EDIT.
// Source: db/sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=db/sqlc/querier.go -destination=mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/P4rz1val22/outreach-tool/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddTagToContact mocks base method.
func (m *MockQuerier) AddTagToContact(ctx context.Context, arg db.AddTagToContactParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTagToContact", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTagToContact indicates an expected call of AddTagToContact.
func (mr *MockQuerierMockRecorder) AddTagToContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagToContact", reflect.TypeOf((*MockQuerier)(nil).AddTagToContact), ctx, arg)
}

// AddTagToThread mocks base method.
func (m *MockQuerier) AddTagToThread(ctx context.Context, arg db.AddTagToThreadParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTagToThread", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTagToThread indicates an expected call of AddTagToThread.
func (mr *MockQuerierMockRecorder) AddTagToThread(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagToThread", reflect.TypeOf((*MockQuerier)(nil).AddTagToThread), ctx, arg)
}

// ArchiveContact mocks base method.
func (m *MockQuerier) ArchiveContact(ctx context.Context, arg db.ArchiveContactParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveContact", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveContact indicates an expected call of ArchiveContact.
func (mr *MockQuerierMockRecorder) ArchiveContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveContact", reflect.TypeOf((*MockQuerier)(nil).ArchiveContact), ctx, arg)
}

// CreateContact mocks base method.
func (m *MockQuerier) CreateContact(ctx context.Context, arg db.CreateContactParams) (db.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, arg)
	ret0, _ := ret[0].(db.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockQuerierMockRecorder) CreateContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockQuerier)(nil).CreateContact), ctx, arg)
}

// CreateContactMethod mocks base method.
func (m *MockQuerier) CreateContactMethod(ctx context.Context, arg db.CreateContactMethodParams) (db.ContactMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContactMethod", ctx, arg)
	ret0, _ := ret[0].(db.ContactMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContactMethod indicates an expected call of CreateContactMethod.
func (mr *MockQuerierMockRecorder) CreateContactMethod(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContactMethod", reflect.TypeOf((*MockQuerier)(nil).CreateContactMethod), ctx, arg)
}

// CreateTag mocks base method.
func (m *MockQuerier) CreateTag(ctx context.Context, arg db.CreateTagParams) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, arg)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockQuerierMockRecorder) CreateTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockQuerier)(nil).CreateTag), ctx, arg)
}

// DeleteContactMethod mocks base method.
func (m *MockQuerier) DeleteContactMethod(ctx context.Context, arg db.DeleteContactMethodParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContactMethod", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContactMethod indicates an expected call of DeleteContactMethod.
func (mr *MockQuerierMockRecorder) DeleteContactMethod(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContactMethod", reflect.TypeOf((*MockQuerier)(nil).DeleteContactMethod), ctx, arg)
}

// GetContactByID mocks base method.
func (m *MockQuerier) GetContactByID(ctx context.Context, arg db.GetContactByIDParams) (db.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByID", ctx, arg)
	ret0, _ := ret[0].(db.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByID indicates an expected call of GetContactByID.
func (mr *MockQuerierMockRecorder) GetContactByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByID", reflect.TypeOf((*MockQuerier)(nil).GetContactByID), ctx, arg)
}

// GetThreadByID mocks base method.
func (m *MockQuerier) GetThreadByID(ctx context.Context, arg db.GetThreadByIDParams) (db.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadByID", ctx, arg)
	ret0, _ := ret[0].(db.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadByID indicates an expected call of GetThreadByID.
func (mr *MockQuerierMockRecorder) GetThreadByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadByID", reflect.TypeOf((*MockQuerier)(nil).GetThreadByID), ctx, arg)
}

// ListContactMethodsByContact mocks base method.
func (m *MockQuerier) ListContactMethodsByContact(ctx context.Context, arg db.ListContactMethodsByContactParams) ([]db.ContactMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContactMethodsByContact", ctx, arg)
	ret0, _ := ret[0].([]db.ContactMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContactMethodsByContact indicates an expected call of ListContactMethodsByContact.
func (mr *MockQuerierMockRecorder) ListContactMethodsByContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContactMethodsByContact", reflect.TypeOf((*MockQuerier)(nil).ListContactMethodsByContact), ctx, arg)
}

// ListContacts mocks base method.
func (m *MockQuerier) ListContacts(ctx context.Context, userID uuid.UUID) ([]db.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContacts", ctx, userID)
	ret0, _ := ret[0].([]db.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContacts indicates an expected call of ListContacts.
func (mr *MockQuerierMockRecorder) ListContacts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContacts", reflect.TypeOf((*MockQuerier)(nil).ListContacts), ctx, userID)
}

// ListContactsByName mocks base method.
func (m *MockQuerier) ListContactsByName(ctx context.Context, arg db.ListContactsByNameParams) ([]db.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContactsByName", ctx, arg)
	ret0, _ := ret[0].([]db.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContactsByName indicates an expected call of ListContactsByName.
func (mr *MockQuerierMockRecorder) ListContactsByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContactsByName", reflect.TypeOf((*MockQuerier)(nil).ListContactsByName), ctx, arg)
}

// ListTags mocks base method.
func (m *MockQuerier) ListTags(ctx context.Context, userID uuid.UUID) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx, userID)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockQuerierMockRecorder) ListTags(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockQuerier)(nil).ListTags), ctx, userID)
}

// ListTagsForContact mocks base method.
func (m *MockQuerier) ListTagsForContact(ctx context.Context, arg db.ListTagsForContactParams) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsForContact", ctx, arg)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForContact indicates an expected call of ListTagsForContact.
func (mr *MockQuerierMockRecorder) ListTagsForContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForContact", reflect.TypeOf((*MockQuerier)(nil).ListTagsForContact), ctx, arg)
}

// ListTagsForThread mocks base method.
func (m *MockQuerier) ListTagsForThread(ctx context.Context, arg db.ListTagsForThreadParams) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsForThread", ctx, arg)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForThread indicates an expected call of ListTagsForThread.
func (mr *MockQuerierMockRecorder) ListTagsForThread(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForThread", reflect.TypeOf((*MockQuerier)(nil).ListTagsForThread), ctx, arg)
}

// ListThreadsByContact mocks base method.
func (m *MockQuerier) ListThreadsByContact(ctx context.Context, arg db.ListThreadsByContactParams) ([]db.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListThreadsByContact", ctx, arg)
	ret0, _ := ret[0].([]db.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListThreadsByContact indicates an expected call of ListThreadsByContact.
func (mr *MockQuerierMockRecorder) ListThreadsByContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListThreadsByContact", reflect.TypeOf((*MockQuerier)(nil).ListThreadsByContact), ctx, arg)
}

// RemoveTagFromContact mocks base method.
func (m *MockQuerier) RemoveTagFromContact(ctx context.Context, arg db.RemoveTagFromContactParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagFromContact", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagFromContact indicates an expected call of RemoveTagFromContact.
func (mr *MockQuerierMockRecorder) RemoveTagFromContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagFromContact", reflect.TypeOf((*MockQuerier)(nil).RemoveTagFromContact), ctx, arg)
}

// RemoveTagFromThread mocks base method.
func (m *MockQuerier) RemoveTagFromThread(ctx context.Context, arg db.RemoveTagFromThreadParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagFromThread", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagFromThread indicates an expected call of RemoveTagFromThread.
func (mr *MockQuerierMockRecorder) RemoveTagFromThread(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagFromThread", reflect.TypeOf((*MockQuerier)(nil).RemoveTagFromThread), ctx, arg)
}

// UpdateContact mocks base method.
func (m *MockQuerier) UpdateContact(ctx context.Context, arg db.UpdateContactParams) (db.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, arg)
	ret0, _ := ret[0].(db.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockQuerierMockRecorder) UpdateContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockQuerier)(nil).UpdateContact), ctx, arg)
}
